---
abstract: 'Libraries/Application I use regularly'
author:
  - 'Adam Stokes <adamjs@cpan.org>'
build_requires:
  Test::Mojo: '0'
  Test::More: '0'
  Test::NoTabs: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.017, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Task-ADAMJS
requires:
  strict: '0'
  warnings: '0'
version: '1.4'
